INSERT INTO specifications(id,productID,specification) VALUES (NULL,1,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,2,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,3,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,4,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,5,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,6,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,7,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,8,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,9,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,10,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,11,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,12,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,13,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,14,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,15,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,16,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,17,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,18,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,19,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,20,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,21,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,22,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,23,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,24,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,25,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,26,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,27,'Genuine crazy horse leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,1,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,2,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,3,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,4,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,5,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,6,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,7,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,8,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,9,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,10,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,11,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,12,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,13,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,14,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,15,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,16,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,17,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,18,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,19,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,20,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,21,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,22,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,23,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,24,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,25,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,26,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,27,'Neoprene lining');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,1,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,2,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,3,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,4,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,5,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,6,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,7,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,8,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,9,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,10,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,11,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,12,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,13,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,14,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,15,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,16,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,17,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,18,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,19,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,20,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,21,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,22,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,23,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,24,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,25,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,26,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,27,'Handpunch perforated brogues');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,1,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,2,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,3,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,4,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,5,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,6,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,7,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,8,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,9,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,10,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,11,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,12,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,13,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,14,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,15,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,16,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,17,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,18,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,19,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,20,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,21,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,22,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,23,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,24,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,25,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,26,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,27,'Cementing construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,1,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,2,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,3,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,4,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,5,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,6,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,7,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,8,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,9,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,10,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,11,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,12,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,13,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,14,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,15,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,16,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,17,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,18,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,19,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,20,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,21,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,22,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,23,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,24,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,25,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,26,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,27,'Cork insole with memory foam');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,1,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,2,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,3,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,4,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,5,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,6,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,7,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,8,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,9,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,10,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,11,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,12,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,13,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,14,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,15,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,16,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,17,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,18,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,19,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,20,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,21,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,22,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,23,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,24,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,25,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,26,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,27,'Handsewn moc toe');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,28,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,29,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,30,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,31,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,32,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,33,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,34,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,35,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,36,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,37,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,38,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,39,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,40,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,41,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,42,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,43,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,44,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,45,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,46,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,47,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,48,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,49,'Italian leather');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,28,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,29,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,30,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,31,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,32,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,33,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,34,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,35,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,36,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,37,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,38,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,39,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,40,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,41,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,42,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,43,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,44,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,45,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,46,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,47,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,48,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,49,'Leather linen');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,28,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,29,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,30,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,31,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,32,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,33,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,34,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,35,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,36,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,37,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,38,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,39,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,40,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,41,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,42,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,43,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,44,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,45,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,46,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,47,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,48,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,49,'Leather outsole');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,28,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,29,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,30,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,31,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,32,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,33,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,34,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,35,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,36,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,37,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,38,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,39,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,40,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,41,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,42,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,43,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,44,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,45,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,46,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,47,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,48,'Goodyear welt construction');
INSERT INTO specifications(id,productID,specification) VALUES (NULL,49,'Goodyear welt construction');


