INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,1,1,'Occaecat esse minim voluptate incididunt id magna labore excepteur laborum adipisicing ad dolore.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,2,2,'Excepteur dolore est cupidatat in laborum.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,3,3,'Non cillum amet occaecat laboris ex sint amet tempor magna nisi reprehenderit amet ullamco ad.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,4,4,'Ut minim aute laboris labore.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,5,5,'Reprehenderit ea excepteur fugiat reprehenderit consequat ipsum nostrud id.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,6,6,'Ea cillum voluptate fugiat id ipsum reprehenderit adipisicing pariatur.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,7,7,'Consectetur nostrud adipisicing occaecat amet elit deserunt excepteur Lorem consequat esse est et irure nostrud.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,8,8,'Duis et deserunt deserunt dolore quis fugiat.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,9,9,'Nulla fugiat consequat ad nisi est non.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,10,10,'Lorem veniam nulla esse laborum duis qui cupidatat elit nostrud excepteur eiusmod.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,11,11,'Ex magna ullamco incididunt est excepteur velit aute.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,12,12,'Aliquip nulla voluptate proident minim laborum nisi aute consectetur exercitation aliquip labore irure.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,13,13,'Occaecat non nulla Lorem voluptate commodo fugiat.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,14,14,'Irure sint consequat sunt minim proident duis ullamco nulla.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,15,15,'Dolore adipisicing nisi aliquip aliqua pariatur proident nulla deserunt duis.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,16,16,'Id qui excepteur pariatur labore cillum mollit ullamco.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,17,17,'Anim amet duis sint anim fugiat duis quis aliqua non deserunt consequat.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,18,18,'Veniam laborum ipsum fugiat proident aliqua exercitation incididunt non pariatur excepteur.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,19,19,'Enim cillum et dolor do deserunt.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,20,20,'Aliqua ex aliqua est elit elit ad.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,21,21,'Labore aliquip excepteur veniam esse.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,22,22,'Laborum excepteur enim quis cillum exercitation reprehenderit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,23,23,'Ea fugiat et exercitation ut nisi minim irure nostrud mollit in minim ipsum aliqua aliqua.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,24,24,'Reprehenderit reprehenderit ipsum laboris in cillum dolor cillum.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,25,25,'Duis nisi incididunt do in proident voluptate Lorem laborum mollit reprehenderit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,26,26,'Est sunt reprehenderit veniam ea ipsum sunt reprehenderit duis sit velit sunt pariatur reprehenderit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,27,27,'In laboris adipisicing cillum esse nulla tempor magna reprehenderit ipsum cupidatat minim labore.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,28,28,'Ipsum occaecat aliquip cupidatat velit ut enim adipisicing occaecat laborum ullamco ipsum qui exercitation aliqua.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,29,29,'Ipsum commodo excepteur ex enim fugiat ex esse laborum ipsum.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,30,30,'Magna excepteur nisi voluptate exercitation culpa quis nostrud aute dolore minim aute mollit proident consectetur.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,31,31,'Cillum nisi ad aute laborum quis et.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,32,32,'Qui esse occaecat laborum incididunt labore pariatur fugiat fugiat eiusmod aliqua consectetur quis adipisicing.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,33,33,'Enim nulla eiusmod magna consectetur culpa laboris aute.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,34,34,'Enim quis reprehenderit commodo sint ad duis tempor.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,35,35,'Ut dolor dolor amet occaecat enim ex aliqua commodo ipsum ad dolor nisi non adipisicing.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,36,36,'Non ea non id laboris elit occaecat reprehenderit magna.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,37,37,'Amet excepteur non pariatur nostrud ea.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,38,38,'Aute Lorem ut aliqua culpa adipisicing nulla sint mollit sit ea dolore occaecat.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,39,39,'Voluptate eu sunt consequat eu sunt exercitation.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,40,40,'Mollit duis ullamco adipisicing excepteur cillum elit dolor magna.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,41,41,'Do consectetur officia ullamco culpa pariatur pariatur proident enim excepteur proident.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,42,42,'Tempor nulla nulla consectetur deserunt anim cillum nisi veniam cillum tempor adipisicing occaecat.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,43,43,'Cupidatat in excepteur est est nostrud proident nostrud sit deserunt est ea.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,44,44,'Officia nisi cillum ut quis aliquip ullamco.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,45,45,'Consectetur officia exercitation labore qui.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,46,46,'Consequat enim incididunt dolore consectetur do commodo voluptate elit consequat esse commodo minim velit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,47,47,'Cillum consectetur labore adipisicing dolor nulla minim occaecat exercitation excepteur nisi elit irure.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,48,48,'Dolore ipsum anim et labore amet nisi consequat adipisicing officia minim magna nisi.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,49,49,'In ullamco minim laborum eiusmod mollit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,50,2,'Excepteur irure reprehenderit fugiat pariatur adipisicing duis quis duis veniam velit occaecat et nisi.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,51,3,'Non adipisicing et sit do.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,52,4,'Eu ex quis excepteur esse ullamco.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,53,5,'Laboris ea magna veniam consectetur adipisicing enim incididunt officia ex est dolore et deserunt.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,54,6,'Sint laborum sint consectetur aliquip exercitation veniam tempor eu velit anim.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,55,7,'Incididunt eiusmod est tempor dolore ad elit elit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,56,8,'Adipisicing aute eu nulla laborum proident sint.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,57,9,'Consectetur irure veniam minim aute incididunt tempor Lorem est non Lorem incididunt magna.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,58,10,'Eiusmod magna nisi nostrud voluptate.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,59,11,'Ut aute irure aliqua laborum labore.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,60,12,'Sunt ex consectetur exercitation officia eu ex nisi cillum consequat elit esse.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,61,13,'Laboris dolor ea consectetur veniam adipisicing incididunt tempor culpa voluptate ea aliquip exercitation sint commodo.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,62,14,'Sit sint exercitation pariatur do.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,63,15,'Id ad cupidatat aliqua labore commodo sit dolore et.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,64,16,'Commodo fugiat Lorem do enim est eiusmod ad Lorem.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,65,17,'Ullamco ipsum officia sunt in deserunt quis sunt mollit ad labore officia elit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,66,18,'Voluptate ex elit nulla commodo amet ea laboris esse irure voluptate.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,67,19,'Culpa mollit eiusmod anim consequat et excepteur mollit in eiusmod quis.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,68,20,'Nulla eiusmod minim velit deserunt qui ut irure cupidatat minim dolor.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,69,21,'Veniam elit est irure laboris culpa ipsum est sint nostrud Lorem elit non.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,70,22,'Occaecat nostrud sunt laborum fugiat aute ut aliqua excepteur aliquip veniam quis.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,71,23,'Sunt ex in occaecat ea.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,72,24,'Mollit laboris sunt consequat quis reprehenderit nisi enim reprehenderit consequat occaecat.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,73,25,'Aliquip fugiat amet eu incididunt ea minim qui officia labore culpa elit consequat.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,74,26,'Culpa laborum Lorem aliqua est enim.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,75,27,'Et cupidatat cillum minim ipsum elit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,76,28,'Minim nulla non sit excepteur eiusmod amet amet commodo ex cupidatat aute.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,77,29,'Cupidatat eiusmod pariatur id nostrud sint qui.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,78,30,'Occaecat ea cillum deserunt et eiusmod cupidatat magna officia quis sint mollit labore minim excepteur.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,79,31,'Qui quis nulla pariatur sint ea aute nisi ullamco cillum et mollit mollit pariatur.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,80,32,'Adipisicing consectetur proident pariatur est occaecat fugiat consectetur magna fugiat amet nisi deserunt.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,81,33,'Adipisicing et in sunt irure voluptate non.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,82,34,'Ex in sit adipisicing aliqua irure sunt velit incididunt amet aliquip aliquip consectetur nulla.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,83,35,'Magna aliquip dolore nisi veniam enim.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,84,36,'Laborum sunt aute excepteur aliqua velit irure veniam quis laboris adipisicing adipisicing.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,85,37,'Magna deserunt dolore non magna ipsum commodo irure dolor.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,86,38,'Non do dolore consectetur incididunt.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,87,39,'Adipisicing ea non incididunt anim.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,88,40,'Proident culpa cupidatat aliquip esse velit Lorem.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,89,41,'Ea proident adipisicing tempor aliquip ipsum.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,90,42,'Sunt esse excepteur laborum eu excepteur magna ullamco.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,91,43,'Commodo cupidatat incididunt esse mollit aliquip laboris qui tempor cillum non non ipsum sit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,92,44,'Sint adipisicing labore magna et qui nulla sint excepteur exercitation.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,93,45,'Ad laboris officia minim cillum velit exercitation et culpa minim labore.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,94,46,'Veniam et ullamco laborum elit aute eiusmod.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,95,47,'Id proident exercitation reprehenderit aute nisi amet sunt irure.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,96,48,'Pariatur reprehenderit in nulla elit voluptate ex est qui nulla quis aute anim commodo.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,97,49,'Non esse laboris fugiat nulla Lorem pariatur quis anim esse.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,98,1,'Non esse laboris fugiat nulla Lorem pariatur quis anim esse.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,99,1,'Magna ullamco magna irure deserunt reprehenderit dolor culpa commodo.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,100,2,'Esse dolor ullamco amet et fugiat ea ea aliquip duis consectetur ea.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,101,3,'Duis ad reprehenderit et proident dolor ipsum Lorem nostrud sunt.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,102,4,'Aliqua voluptate tempor fugiat laboris elit adipisicing deserunt voluptate fugiat deserunt.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,103,5,'Et qui nostrud voluptate ut veniam ut deserunt officia nulla culpa.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,104,6,'Eu excepteur ut occaecat sunt tempor ex exercitation nulla velit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,105,7,'Velit occaecat ut ex adipisicing nulla nulla magna deserunt pariatur velit consectetur officia dolore.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,106,8,'Qui qui ut cillum labore eu do anim ad cillum proident.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,107,9,'Adipisicing cupidatat consectetur amet pariatur sint.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,108,10,'Esse pariatur laborum sunt magna quis anim.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,109,11,'Amet ea eiusmod elit aute.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,110,12,'Et occaecat voluptate voluptate elit cillum est velit elit est ipsum et ullamco amet id.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,111,13,'Duis ea anim nisi nostrud.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,112,14,'Voluptate quis est sunt officia sunt labore elit consectetur anim eiusmod.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,113,15,'Velit ea nisi fugiat sint incididunt ipsum pariatur incididunt veniam et laboris deserunt ad esse.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,114,16,'Incididunt fugiat commodo cupidatat ut culpa tempor.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,115,17,'Ut ea laboris cupidatat elit mollit fugiat.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,116,18,'Sint cillum consequat qui irure nisi aliquip laborum cillum.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,117,19,'Consectetur ea minim non exercitation.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,118,20,'Nisi qui duis esse pariatur dolore eu sit dolor amet laboris est.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,119,21,'Sunt magna reprehenderit exercitation ullamco.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,120,22,'Dolor labore elit aute cupidatat est consectetur ad excepteur dolor nulla aute aliquip laborum ex.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,121,23,'Nostrud labore esse nostrud ipsum aliquip nostrud Lorem dolor excepteur officia quis velit amet.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,122,24,'In duis irure est qui ipsum.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,123,25,'In ut incididunt incididunt et adipisicing ea.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,124,26,'Laborum quis cupidatat do ut velit ipsum proident sunt magna.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,125,27,'Commodo veniam excepteur consectetur proident amet enim Lorem culpa anim nulla Lorem dolore consectetur minim.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,126,28,'Dolore dolore qui ex dolor minim ipsum elit in pariatur.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,127,29,'Magna consequat aliqua qui consectetur.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,128,30,'Ipsum adipisicing elit culpa aute reprehenderit veniam cillum aliqua laboris est tempor tempor ullamco.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,129,31,'Magna laborum cupidatat deserunt aliqua est laboris adipisicing.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,130,32,'Elit ea esse irure ullamco non tempor consectetur est esse.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,131,33,'Pariatur commodo veniam quis sit sint.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,132,34,'Dolor sunt sint pariatur velit amet eiusmod amet excepteur esse.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,133,35,'Do qui ad aute officia sit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,134,36,'Incididunt qui ipsum laborum ullamco commodo qui qui pariatur magna ut.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,135,37,'Dolor proident cillum do et aute mollit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,136,38,'Consequat magna veniam officia cillum esse Lorem mollit laborum id ad.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,137,39,'Anim ut velit dolore proident minim pariatur.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,138,40,'Eu commodo esse anim aute enim consequat ipsum voluptate.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,139,41,'Do et fugiat nostrud sit anim quis aute laborum exercitation in.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,140,42,'Consectetur labore ipsum duis voluptate ea elit aute.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,141,43,'Laborum qui et cillum nostrud magna.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,142,44,'Officia cupidatat aliqua et sint incididunt.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,143,45,'Aute officia veniam minim sit reprehenderit anim veniam voluptate amet veniam incididunt Lorem velit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,144,46,'Ex exercitation ad esse dolore ullamco Lorem dolor.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,145,47,'Pariatur aliqua sint aute ullamco dolore eiusmod.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,146,48,'Sit adipisicing commodo aute ullamco exercitation incididunt.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,147,49,'Id in cillum ullamco ad nostrud exercitation proident nulla do dolore in.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,148,1,'Et ut excepteur magna nisi minim non esse sunt.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,149,2,'Proident Lorem non minim cupidatat dolore.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,150,3,'Laboris exercitation pariatur excepteur reprehenderit commodo ea veniam occaecat ullamco.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,151,4,'Consequat aute sunt reprehenderit in sint occaecat culpa pariatur minim sunt id sit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,152,5,'Dolor aliqua tempor et eiusmod irure mollit deserunt nisi.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,153,6,'Aliquip laboris dolore Lorem veniam eu minim non nostrud in excepteur aliquip est laborum.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,154,7,'Enim magna excepteur aute anim elit qui id.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,155,8,'Dolore reprehenderit sunt ea enim excepteur magna eiusmod nostrud reprehenderit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,156,9,'Commodo consequat nulla est occaecat amet amet sunt.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,157,10,'Quis laborum occaecat cillum irure labore officia commodo officia laboris culpa.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,158,11,'Aliquip aliquip eu non fugiat voluptate velit irure veniam.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,159,12,'Voluptate ea cupidatat non reprehenderit id cillum cillum eiusmod.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,160,13,'Velit aliqua dolor dolor ea in officia irure elit deserunt deserunt excepteur.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,161,14,'Consequat magna duis enim id ullamco ea dolore amet fugiat esse nulla veniam consectetur eiusmod.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,162,15,'Elit culpa minim aliquip veniam dolore incididunt.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,163,16,'Aliqua ipsum consequat nulla pariatur commodo est voluptate occaecat adipisicing reprehenderit dolore.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,164,17,'Irure cillum dolore reprehenderit velit tempor ipsum nostrud sunt minim excepteur ullamco magna laboris.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,165,18,'Qui est pariatur excepteur ea elit ex laboris Lorem ipsum anim.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,166,19,'Consequat nostrud excepteur quis officia aute anim velit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,167,20,'Commodo enim dolor labore aute.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,168,21,'Quis et quis ipsum commodo elit cupidatat ipsum qui aute in consectetur nulla proident voluptate.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,169,22,'Enim ut aliqua aliquip minim voluptate ipsum nostrud ullamco deserunt nostrud nostrud.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,170,23,'Dolore elit id occaecat sint aute aliquip irure ullamco aliquip ut.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,171,24,'Et Lorem incididunt nostrud ut et pariatur consequat sit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,172,25,'Do anim culpa culpa ullamco esse ea enim nulla adipisicing exercitation occaecat pariatur id.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,173,26,'Deserunt do aute veniam qui nulla excepteur esse consectetur amet eiusmod.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,174,27,'Ullamco ex elit nulla veniam aute cupidatat tempor veniam irure dolore sit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,175,28,'Nulla sit in velit tempor cupidatat id consequat labore ullamco dolor irure excepteur sunt.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,176,29,'Sunt incididunt cupidatat quis consequat duis ea officia sint.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,177,30,'Dolore sit ex tempor incididunt exercitation anim deserunt labore eiusmod labore eu minim cillum quis.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,178,31,'Dolore minim aliqua incididunt ad proident duis cupidatat est.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,179,32,'Consequat elit ex fugiat ex exercitation enim et sunt labore.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,180,33,'Adipisicing nulla exercitation eu cillum tempor eiusmod anim velit veniam officia anim enim.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,181,34,'Culpa officia deserunt anim qui ut ad commodo dolor duis nulla sint pariatur voluptate eu.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,182,35,'Sint anim non enim cillum ea sint nisi fugiat id minim id.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,183,36,'Ex id sint magna consequat sunt proident reprehenderit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,184,37,'Ad ullamco sunt consequat non.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,185,38,'Fugiat velit elit sunt non aliqua pariatur adipisicing.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,186,39,'Excepteur eiusmod laborum eu duis.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,187,40,'Et officia amet minim qui amet mollit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,188,41,'Reprehenderit consectetur ullamco ipsum elit sunt in cupidatat ex officia fugiat labore fugiat.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,189,42,'Ut quis dolor eiusmod ex.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,190,43,'Do incididunt ea nisi officia consectetur nulla consectetur amet laborum nisi labore enim est occaecat.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,191,44,'Nostrud pariatur veniam do eiusmod do proident nisi consequat labore amet fugiat aliqua ullamco elit.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,192,45,'Voluptate duis officia occaecat reprehenderit excepteur consectetur mollit laborum ipsum.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,193,46,'Elit esse tempor aliqua mollit qui laborum pariatur ea consequat do aliqua.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,194,47,'Commodo ex ut velit anim occaecat eu in deserunt sunt ullamco enim incididunt fugiat.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,195,48,'Deserunt culpa nisi incididunt enim proident proident anim culpa eiusmod laboris dolore cillum laboris.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,196,49,'Consequat voluptate ut officia sunt dolore excepteur laboris eu eu proident qui ut deserunt excepteur.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,197,1,'Elit esse tempor aliqua mollit qui laborum pariatur ea consequat do aliqua.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,198,2,'Commodo ex ut velit anim occaecat eu in deserunt sunt ullamco enim incididunt fugiat.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,199,3,'Deserunt culpa nisi incididunt enim proident proident anim culpa eiusmod laboris dolore cillum laboris.');
INSERT INTO reviews(id,customerID,productID,review) VALUES (NULL,200,4,'Consequat voluptate ut officia sunt dolore excepteur laboris eu eu proident qui ut deserunt excepteur.');
